import {
  USER_LOGIN_ACTION,
  USER_REGISTER_ACTION,
  USER_DETAILS_ACTION,
  USER_UPDATE_PROFILE_ACTION,
  USER_LIST_ACTION,
  USER_REQUEST_ACTION,
  USER_UPDATE_ACTION,
} from '../constants/userConstants';

//User Login Interface
interface USER_LOGIN_REQUEST {
  type: USER_LOGIN_ACTION.USER_LOGIN_REQUEST;
  payload?: object;
}
interface USER_LOGIN_SUCCESS {
  type: USER_LOGIN_ACTION.USER_LOGIN_SUCCESS;
  payload: object;
}
interface USER_LOGIN_FAIL {
  type: USER_LOGIN_ACTION.USER_LOGIN_FAIL;
  payload: object;
}
interface USER_LOGOUT {
  type: USER_LOGIN_ACTION.USER_LOGOUT;
  payload?: object;
}

//User Register Interface
interface USER_REGISTER_REQUEST {
  type: USER_REGISTER_ACTION.USER_REGISTER_REQUEST;
  payload?: object;
}
interface USER_REGISTER_SUCCESS {
  type: USER_REGISTER_ACTION.USER_REGISTER_SUCCESS;
  payload: object;
}
interface USER_REGISTER_FAIL {
  type: USER_REGISTER_ACTION.USER_REGISTER_FAIL;
  payload: object;
}
interface USER_REGISTER_LOGOUT {
  type: USER_REGISTER_ACTION.USER_REGISTER_LOGOUT;
  payload?: object;
}

//User Details Interface
interface USER_DETAILS_REQUEST {
  type: USER_DETAILS_ACTION.USER_DETAILS_REQUEST;
  payload?: object;
}
interface USER_DETAILS_SUCCESS {
  type: USER_DETAILS_ACTION.USER_DETAILS_SUCCESS;
  payload: object;
}
interface USER_DETAILS_FAIL {
  type: USER_DETAILS_ACTION.USER_DETAILS_FAIL;
  payload: object;
}
interface USER_DETAILS_RESET {
  type: USER_DETAILS_ACTION.USER_DETAILS_RESET;
  payload?: object;
}

//User Update Interface
interface USER_UPDATE_PROFILE_REQUEST {
  type: USER_UPDATE_PROFILE_ACTION.USER_UPDATE_PROFILE_REQUEST;
  payload?: object;
}
interface USER_UPDATE_PROFILE_SUCCESS {
  type: USER_UPDATE_PROFILE_ACTION.USER_UPDATE_PROFILE_SUCCESS;
  payload: object;
}
interface USER_UPDATE_PROFILE_FAIL {
  type: USER_UPDATE_PROFILE_ACTION.USER_UPDATE_PROFILE_FAIL;
  payload: object;
}

//User List Interface
interface USER_LIST_REQUEST {
  type: USER_LIST_ACTION.USER_LIST_REQUEST;
  payload?: object;
}
interface USER_LIST_SUCCESS {
  type: USER_LIST_ACTION.USER_LIST_SUCCESS;
  payload: object;
}
interface USER_LIST_FAIL {
  type: USER_LIST_ACTION.USER_LIST_FAIL;
  payload: object;
}
interface USER_LIST_RESET {
  type: USER_LIST_ACTION.USER_LIST_RESET;
  payload?: object;
}

//User Delete Interface
interface USER_DELETE_REQUEST {
  type: USER_REQUEST_ACTION.USER_DELETE_REQUEST;
  payload?: object;
}
interface USER_DELETE_SUCCESS {
  type: USER_REQUEST_ACTION.USER_DELETE_SUCCESS;
  payload?: object;
}
interface USER_DELETE_FAIL {
  type: USER_REQUEST_ACTION.USER_DELETE_FAIL;
  payload: object;
}

//User Update Interface
interface USER_UPDATE_REQUEST {
  type: USER_UPDATE_ACTION.USER_UPDATE_REQUEST;
  payload?: object;
}
interface USER_UPDATE_SUCCESS {
  type: USER_UPDATE_ACTION.USER_UPDATE_SUCCESS;
  payload?: object;
}
interface USER_UPDATE_FAIL {
  type: USER_UPDATE_ACTION.USER_UPDATE_FAIL;
  payload: object;
}
interface USER_UPDATE_RESET {
  type: USER_UPDATE_ACTION.USER_UPDATE_RESET;
  payload?: object;
}

export type Action =
  | USER_LOGIN_REQUEST
  | USER_LOGIN_SUCCESS
  | USER_LOGIN_FAIL
  | USER_LOGOUT
  | USER_REGISTER_REQUEST
  | USER_REGISTER_SUCCESS
  | USER_REGISTER_FAIL
  | USER_REGISTER_LOGOUT
  | USER_DETAILS_REQUEST
  | USER_DETAILS_SUCCESS
  | USER_DETAILS_FAIL
  | USER_UPDATE_PROFILE_REQUEST
  | USER_UPDATE_PROFILE_SUCCESS
  | USER_UPDATE_PROFILE_FAIL
  | USER_DETAILS_RESET
  | USER_LIST_REQUEST
  | USER_LIST_SUCCESS
  | USER_LIST_FAIL
  | USER_LIST_RESET
  | USER_DELETE_REQUEST
  | USER_DELETE_SUCCESS
  | USER_DELETE_FAIL
  | USER_UPDATE_REQUEST
  | USER_UPDATE_SUCCESS
  | USER_UPDATE_FAIL
  | USER_UPDATE_RESET;
